CREATE TABLE version(id INTEGER PRIMARY KEY AUTOINCREMENT, 
version TEXT NOT NULL UNIQUE, 
deploy_time DATETIME);
INSERT INTO version VALUES (NULL,'0.2.0',DATETIME('now'));
CREATE TABLE time(id INTEGER PRIMARY KEY AUTOINCREMENT, 
timestamp DATETIME);
CREATE TABLE todo(id INTEGER PRIMARY KEY AUTOINCREMENT, todo_text TEXT NOT NULL UNIQUE);
CREATE TABLE todo_at_time(todo_id INTEGER NOT NULL UNIQUE,time_id INTEGER NOT NULL UNIQUE);