CREATE TABLE version(id INTEGER PRIMARY KEY AUTOINCREMENT, 
version TEXT NOT NULL UNIQUE, 
deploy_time DATETIME);
INSERT INTO version VALUES (NULL,'0.1.0',DATETIME('now'));
CREATE TABLE time(id INTEGER PRIMARY KEY AUTOINCREMENT, 
timestamp DATETIME, 
todo_id INTEGER NOT NULL,
FOREIGN KEY(todo_id) REFERENCES todo(id));
CREATE TABLE todo(id INTEGER PRIMARY KEY AUTOINCREMENT, todo_text TEXT NOT NULL UNIQUE);